# Generated by Django 4.2.23 on 2025-08-18 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('totp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': '分组', 'verbose_name_plural': '分组'},
        ),
        migrations.AlterModelOptions(
            name='totpentry',
            options={'verbose_name': '密钥', 'verbose_name_plural': '密钥'},
        ),
    ]
