# Generated by Django 4.2.23 on 2025-09-23 13:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("totp", "0002_alter_group_options_alter_totpentry_options"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="totpentry",
            name="totp_totpen_user_id_e0f72d_idx",
        ),
        migrations.AlterUniqueTogether(
            name="totpentry",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="totpentry",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="totpentry",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterUniqueTogether(
            name="totpentry",
            unique_together={("user", "name", "is_deleted")},
        ),
        migrations.AddIndex(
            model_name="totpentry",
            index=models.Index(
                fields=["user", "name", "is_deleted"],
                name="totp_totpen_user_id_488923_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="totpentry",
            index=models.Index(
                fields=["user", "is_deleted", "deleted_at"],
                name="totp_totpen_user_id_231cdf_idx",
            ),
        ),
        ]