# Generated by Django 4.2.23 on 2025-09-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("totp", "0003_add_recycle_bin_fields"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="totpentry",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="totpentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("user", "name"),
                name="uniq_active_totp_entry",
            ),
        ),
    ]