# Generated by Codex on 2025-xx-xx
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("totp", "0004_alter_totpentry_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OneTimeLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token_hash", models.CharField(max_length=128, unique=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("max_views", models.PositiveSmallIntegerField(default=1)),
                ("view_count", models.PositiveSmallIntegerField(default=0)),
                ("first_viewed_at", models.DateTimeField(blank=True, null=True)),
                ("last_viewed_at", models.DateTimeField(blank=True, null=True)),
                ("last_view_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("last_view_user_agent", models.CharField(blank=True, max_length=256)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_one_time_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="one_time_links",
                        to="totp.totpentry",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="onetimelink",
            index=models.Index(fields=["entry", "expires_at"], name="one_time_entry_exp_idx"),
        ),
        migrations.AddIndex(
            model_name="onetimelink",
            index=models.Index(fields=["created_by", "created_at"], name="one_time_created_idx"),
        ),
    ]
