# Generated by Codex
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("totp", "0005_onetimelink"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80)),
                ("frequency_hours", models.PositiveIntegerField(default=24)),
                ("keep_last", models.PositiveSmallIntegerField(default=5)),
                ("storage", models.CharField(choices=[("db", "数据库")], default="db", max_length=16)),
                ("is_active", models.BooleanField(default=True)),
                ("next_run_at", models.DateTimeField()),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backup_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["next_run_at"],
            },
        ),
        migrations.CreateModel(
            name="BackupArchive",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80)),
                ("storage", models.CharField(choices=[("db", "数据库")], default="db", max_length=16)),
                ("encryption", models.CharField(choices=[("user", "用户密码"), ("system", "系统密钥")], default="user", max_length=16)),
                ("encrypted_payload", models.TextField()),
                ("salt", models.CharField(blank=True, max_length=64)),
                ("iterations", models.PositiveIntegerField(default=390000)),
                ("entry_count", models.PositiveIntegerField(default=0)),
                ("size_bytes", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archives",
                        to="totp.backupschedule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backup_archives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
