# Generated by Django 4.2.24 on 2025-09-25 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('totp', '0006_backup_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backuparchive',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='backuparchive',
            name='user',
        ),
        migrations.RemoveField(
            model_name='backupschedule',
            name='user',
        ),
        migrations.RenameIndex(
            model_name='onetimelink',
            new_name='totp_onetim_entry_i_8a1b1c_idx',
            old_name='one_time_entry_exp_idx',
        ),
        migrations.RenameIndex(
            model_name='onetimelink',
            new_name='totp_onetim_created_ed0154_idx',
            old_name='one_time_created_idx',
        ),
        migrations.DeleteModel(
            name='BackupArchive',
        ),
        migrations.DeleteModel(
            name='BackupSchedule',
        ),
    ]
