# Generated by Django 4.2.23 on 2025-10-16 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('totp', '0012_totpentryaudit'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='totpentry',
            new_name='totp_totpen_team_id_a89936_idx',
            old_name='totpentry_team_name_idx',
        ),
        migrations.RenameIndex(
            model_name='totpentry',
            new_name='totp_totpen_team_id_e45175_idx',
            old_name='totpentry_team_created_idx',
        ),
    ]
