# Generated by Django 4.2.23 on 2026-03-15 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('totp', '0013_rename_totpentry_team_name_idx_totp_totpen_team_id_a89936_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='totpentry',
            new_name='totp_totpen_team_id_a89936_idx',
            old_name='totpentry_team_name_idx',
        ),
        migrations.RenameIndex(
            model_name='totpentry',
            new_name='totp_totpen_team_id_e45175_idx',
            old_name='totpentry_team_created_idx',
        ),
    ]
