# Generated by Django 4.2.23 on 2026-03-15 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("totp", "0014_rename_totpentry_team_name_idx_totp_totpen_team_id_a89936_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamAudit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(choices=[("team_created", "创建团队"), ("team_renamed", "修改团队名称"), ("invite_sent", "发送邀请"), ("invite_updated", "更新邀请"), ("invite_cancelled", "取消邀请"), ("invite_accepted", "接受邀请"), ("invite_declined", "拒绝邀请"), ("member_role_changed", "成员角色调整"), ("member_removed", "移除成员"), ("member_left", "成员退出"), ("links_revoked_all", "撤销全部分享链接")], db_index=True, max_length=32)),
                ("old_value", models.CharField(blank=True, max_length=200)),
                ("new_value", models.CharField(blank=True, max_length=200)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="totp_team_audits", to=settings.AUTH_USER_MODEL)),
                ("target_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="totp_team_audits_target", to=settings.AUTH_USER_MODEL)),
                ("team", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="audits", to="totp.team")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="teamaudit",
            index=models.Index(fields=["team", "created_at"], name="totp_teama_team_id_7d6676_idx"),
        ),
        migrations.AddIndex(
            model_name="teamaudit",
            index=models.Index(fields=["team", "action", "created_at"], name="totp_teama_team_id_620bf1_idx"),
        ),
    ]

